server:
  port: 8189
  servlet:
    context-path: /ezplan
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=ezplan
    username: postgres
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
jwt:
  secret: ddn5d7dkjcsghsjpqww87g98hf9834345345345r9sf827fs7bf8ds9g67ds
